# Adding the shared folder to the pythonpath allows development work for the current repository
# given that the actual python app is located on the root, e.g., openwind/openwind
#- name: openwind | Add PYTHONPATH to bashrc
#  lineinfile: dest="/home/vagrant/.bashrc" line="export PYTHONPATH=/vagrant"

  - name: openwind | Change owner of anaconda directory (otherwise later provisioning will fail)
    shell: "sudo chown -R vagrant {{ conda_dir }}/"
    ignore_errors: yes

  - name: openwind | create file activate.d/env_vars.sh in conda env
    file:
      path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/activate.d/env_vars.sh"
      state: touch
      mode: u=rw,g=r,o=r
  
  - name: openwind | Set comment in environment variable file
    lineinfile:
        path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/activate.d/env_vars.sh"
        insertbefore: BOF
        line: "#!/bin/bash"
  
  - name: openwind | Set PYTHONPATH environment variable required by Nansat for use in Jupyter
    lineinfile:
        path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/activate.d/env_vars.sh"
        line: "export PYTHONPATH=/vagrant:{{ project_home }}:{{ project_home }}/{{ project_name }}"
  
  - name: openwind | Set PROJ_LIB environment variable required by Nansat for use in Jupyter
    lineinfile:
        path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/activate.d/env_vars.sh"
        line: "export PROJ_LIB={{ conda_dir }}/envs/{{ env_name }}/share/proj"
  
  #- name: openwind | create file deactivate.d/env_vars.sh in conda env
  #  file:
  #    path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/deactivate.d/env_vars.sh"
  #    state: touch
  #    mode: u=rw,g=r,o=r
  # 
  #  - name: openwind | Set comment in environment variable file
  #    lineinfile:
  #        path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/deactivate.d/env_vars.sh"
  #        line: "#!/bin/bash"
  #  
  #  - name: openwind | Unset PYTHONPATH environment variable when deactivating env
  #    lineinfile:
  #        path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/deactivate.d/env_vars.sh"
  #        line: "unset PYTHONPATH=/vagrant:{{ project_home }}:{{ project_home }}/{{ project_name }}"
  #  
  #  - name: openwind | Unset PROJ_LIB environment variable when deactivating env
  #    lineinfile:
  #        path: "{{ conda_dir }}/envs/{{ env_name }}/etc/conda/deactivate.d/env_vars.sh"
  #        line: "unset PROJ_LIB={{ conda_dir }}/envs/{{ env_name }}/share/proj"
  
  - name: openwind | Set cron shell to bash 
    cron: 
        name: SHELL
        env: yes
        job: /bin/bash
  
  - name: openwind | Set up daily processing
    cron: 
        name: "Daily processing"
        special_time: daily
        job: "{{ project_home }}/daily_sync.sh"
  
  - name: openwind | Create shell script for daily data sync and wind processing
    file:
      path: "{{ project_home }}/daily_sync.sh"
      state: touch
      mode: u=rwx,g=r,o=r

  - name: openwind | Sync script heading
    lineinfile:
        path: "{{ project_home }}/daily_sync.sh"
        insertbefore: BOF
        line: "#!/bin/bash"

  - name: openwind | Sync script content
    blockinfile:
        path: "{{ project_home }}/daily_sync.sh"
        block: |
            export PROJ_LIB={{ conda_dir }}/envs/{{ env_name }}/share/proj
            source {{ conda_dir }}/bin/activate {{ env_name }}
            cd {{ project_home }}/{{ project_name }}
            # Sync S1A
            {{ conda_dir }}/envs/{{ env_name }}/bin/python {{ project_home }}/{{ project_name }}/manage.py ingest_thredds_crawl http://nbstds.met.no/thredds/catalog/NBS/S1A/`date -d "yesterday 00:00" '+%Y/%m/%d'`/catalog.html
            # Sync S1B
            {{ conda_dir }}/envs/{{ env_name }}/bin/python {{ project_home }}/{{ project_name }}/manage.py ingest_thredds_crawl http://nbstds.met.no/thredds/catalog/NBS/S1B/`date -d "yesterday 00:00" '+%Y/%m/%d'`/catalog.html
            # Sync Arome Arctic
            {{ conda_dir }}/envs/{{ env_name }}/bin/python {{ project_home }}/{{ project_name }}/manage.py ingest_thredds_crawl https://thredds.met.no/thredds/catalog/aromearcticarchive/`date -d "yesterday 00:00" '+%Y/%m/%d'`/catalog.html --filename arome_arctic_vtk.*
            # Process S1 wind
            {{ conda_dir }}/envs/{{ env_name }}/bin/python {{ project_home }}/{{ project_name }}/manage.py process_sentinel1_wind --date `date -d "yesterday 00:00" '+%Y-%m-%d'`

