---
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scipy
  - django
  - binutils
  - pyproj
  - gdal
  - libspatialite
  - pythesint
  - nansat
  - nose
  - coveralls
  - mock
  - ipython
  - ipdb
  - thredds_crawler
